require(depth)
require(MASS)
require(psych)
require(fda)
require(mvoutlier)
require(robustbase)
require(fda)
require(RandomFields)
require(scatterplot3d)
require(aplpack)
require(depth)
require(depthTools)
require(matrixStats)
require(fda.usc)
require(deldir)
require(rainbow)
require(grid)
require(ggplot2)
require(reshape2)
require(refund.shiny)
require(car)

source("Data_add.R")
source("Data0.R")
source("Data1.R")
source("Data2.R")
source("Data3.R")
source("Data4.R")
source("Data5.R")
source("Data6.R")
source("Data7.R")
source("Data8.R")
source("Data9.R")
source("Model1.R")
source("Model2.R")
source("Model3.R")
source("MFHD.R")
source("DirOut.R")
source("calcSigma.R")
source("cm.R")
source("mcd.est.R")
source("MDATA1.R")
source("MDATA2.R")
source("MDATA3.R")
source("MDATA4.R")
source("MDATA5.R")
source("MDATA11.R")
source("MDATA12.R")
source("bivmbd.R")
source("MFHD_bagplot.R")
source("facCal.R")
source("testoutlier.uni.R")
source("OutGramAdj.R")
source("facCal_num.R")


RBD2=function(data,prop=0.55,power=1)
{
n=dim(data)[2]
p=dim(data)[1]
dmat=matrix(0,n,p)
medvec=apply(data,1,median)
madvec=apply(data,1,mad)
dmat=(data-medvec)/(madvec)
mr=apply(dmat,2,mean)
var=apply(dmat,2,var)
M=cbind(mr,var^(power))
me=med(M,method="Liu")$median
cov=cov.rob(M,method="mcd",nsamp="best",quantile.used=floor(n*prop))$cov
#me=cov.mcd(M)$center
D=mahalanobis(M,me,cov)
D=D
mr=mr
var=var
list(D=D,mr=mr,var=var)
}



